script: bundle exec rake
sudo: false
cache: bundler
language: ruby
rvm:
- 2.4.2
- 2.3.5
- 2.2.8
before_script:
- 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email: false
env:
  global:
    secure: J350gO3bvDLfB7fwPyrt+WqpSwWzF23W0woYv0xU7MG1uXvE4X8PXgnlELCaj+Ps0bo4Rn8Ve7FzUyMlnGtUCB4W8/opF2KjMkDMov/bEG2FMJBjmrQXB4KrDsJk0V3N5lnTgizCB8Yk5l5qmQ+N6bPxiDJtFtQt6bWtce7/18M=
