script: bundle exec rspec
sudo: false
cache: bundler
language: ruby
rvm:
- 2.3.0
- '2.2'
- '2.1'
notifications:
  email: false
env:
  global:
    secure: izDHU1YyhBSpzaWjxhJUhcha6GGXSGqYDmHpU1AtYddZHJKTiVo1qPdMxl90xrdSQR4rHNibrV48yx4rggz5w9+YYqwCNVSLkWJCKIqzil6h7IvSZCGmPz8cmK7TFtM6hCzaNezhGrmczCOvRiIyofsCvCqroYIWxmsRRc9mwOY=
